sudo: required

services:
  - docker

before_install:
  - docker-compose up -d

script:
  - docker run authentication /bin/sh -c "cd /src; npm test"
  - docker run webfacade /bin/sh -c "cd /src; npm test"
after_success:
  - gem install net-scp
  - gem install net-ssh
  - ruby deploy.rb