sudo: required

services:
  - docker

before_install:
  - docker-compose up -d

script:
  - docker run proepdockercontainerservices_dataservice /bin/sh -c "cd /src; npm test"
  - docker run proepdockercontainerservices_authentication /bin/sh -c "cd /src; npm test"
  - docker run proepdockercontainerservices_webfacade /bin/sh -c "cd /src; npm test"
  - gem install net-scp
  - gem install net-ssh
  - ruby deploy.rb