sudo: required

services:
  - docker

before_install:
  - docker-compose up -d

script:
  - docker exec -t proepdockercontainerservices_dataservice_1 /bin/sh -c "cd /src; npm test"
  - docker exec -t proepdockercontainerservices_authentication_1 /bin/sh -c "cd /src; npm test"
  - docker exec -t proepdockercontainerservices_webfacade_1 /bin/sh -c "cd /src; npm test"
  - docker exec -t proepdockercontainerservices_payment_1 /bin/sh -c "cd /src; npm test"
after_success:
  - gem install net-scp
  - gem install net-ssh
  - ruby deploy.rb
branches:
  only:
  - master