version: '2'
services:
  authentication:
    build: authentication
    links:
     - dataservice
    ports:
     - "9000:9000"
  webfacade:
    build: webfacade
    links:
     - authentication
    ports:
     - "9090:9090"
  streamtranscoder:
    build: streamtranscoder
    ports:
     - "1984:1984"
     - "1776:1776"
  dataservice:
    build: dataservice
    links:
     - postgresql
  postgresql:
    image: "postgres:alpine"
    restart: always
    volumes:
     - ../dockervolumes/postgres-data:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=show_me_db
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=showme