version: '2.1'
services:
  authentication:
    build: authentication
    links:
     - dataservice
    ports:
     - "9000:9000"
  webfacade:
    build: webfacade
    restart: always
    depends_on:
      rabbit:
        condition: service_healthy
    links:
     - authentication
     - stream
     - rabbit
    ports:
     - "9090:9090"
  phonefacade:
    build: phonefacade
    restart: always
    links:
     - authentication
     - stream
    ports:
     - "1903:1903"
  streamtranscoder:
    build: streamtranscoder
    ports:
     - "1984:1984"
     - "1776:1776"
  dataservice:
    build: dataservice
    links:
     - postgresql
    ports:
     - "2000:1984"
  postgresql:
    image: "postgres:alpine"
    restart: always
    volumes:
     - ../dockervolumes/postgres-data:/var/lib/postgresql/data
    ports:
     - "6000:5432"
    environment:
     - POSTGRES_DB=show_me_db
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=showme
  payment:
      build: payment
      ports:
       - "1996:1996"
       - "1997:1997"
  rabbit:
     container_name: dev_rabbit
     hostname: rabbit
     image: healthcheck/rabbitmq
     environment:
        - RABBITMQ_DEFAULT_USER = user
        - RABBITMQ_DEFAULT_PASS = user
     ports:
        - "5672:5672"
        - "15672:15672"
  integrationtest:
    build: integrationtest
    links:
      - webfacade
      - phonefacade
  stream:
    build: stream
    restart: always
    depends_on:
      rabbit:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
     - rabbit
     - redis
    ports:
     - "1950:1950"
  redis:
    image: healthcheck/redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports: 
      - "6379:6379"
    volumes:
     - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
     - ../dockervolumes/redis-data:/data