version: '2'
services:
  authentication:
    build: authentication
    links:
     - dataservice
    ports:
     - "9000:9000"
  webfacade:
    build: webfacade
    links:
     - authentication
    ports:
     - "9090:9090"
  phonefacade:
    build: phonefacade
    links:
     - authentication
    ports:
     - "1903:1903"
  streamtranscoder:
    build: streamtranscoder
    ports:
     - "1984:1984"
     - "1776:1776"
  dataservice:
    build: dataservice
    links:
     - postgresql
  postgresql:
    image: "postgres:alpine"
    restart: always
    volumes:
     - ../dockervolumes/postgres-data:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=show_me_db
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=showme
  payment:
      build: payment
      ports:
       - "1996:1996"
  rabbit:
     container_name: dev_rabbit
     hostname: rabbit
     image: rabbitmq:3.6.6-management
     environment:
        - RABBITMQ_DEFAULT_USER = user
        - RABBITMQ_DEFAULT_PASS = user
     ports:
        - "5672:5672"
        - "15672:15672"
  integrationtest:
      build: integrationtest
      links:
        - webfacade