version: '2'
services:
  authentication:
    build: authentication
    ports:
     - "9000:9000"
  webfacade:
    build: webfacade
    ports:
     - "9090:9090"
  dataservice:
    build: dataservice
    links:
     - postgresql
    ports:
     - "1984:1984"
  postgresql:
    image: "postgres:alpine"
    restart: always
    environment:
      - POSTGRES_DB=show_me_db
      - PSOTGRES_USER=showme
      - POSTGRES_PASSWORD=showme