version: '2.1'
services:
  authentication:
    build: authentication
    links:
     - dataservice
    ports:
     - "9000:9000"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  webfacade:
    build: webfacade
    restart: always
    depends_on:
      rabbit:
        condition: service_healthy
    links:
     - authentication
     - payment
     - stream
     - rabbit
    ports:
     - "9090:9090"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  phonefacade:
    build: phonefacade
    restart: always
    links:
     - authentication
     - stream
    ports:
     - "1903:1903"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  streamtranscoder:
    build: streamtranscoder
    ports:
     - "1984:1984"
     - "1776:1776"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  dataservice:
    build: dataservice
    links:
     - postgresql
    ports:
     - "2000:1984"
    depends_on:
      postgresql:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  postgresql:
    image: "healthcheck/postgres:alpine"
    restart: always
    volumes:
     - ../dockervolumes/postgres-data:/var/lib/postgresql/data
    ports:
     - "6000:5432"
    environment:
     - POSTGRES_DB=show_me_db
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=showme
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  payment:
    build: payment
    depends_on:
      rabbit:
        condition: service_healthy
    links:
     - dataservice
     - rabbit
    ports:
      - "1996:1996"
      - "1997:1997"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  rabbit:
    container_name: dev_rabbit
    hostname: rabbit
    image: healthcheck/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER = user
      - RABBITMQ_DEFAULT_PASS = user
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  integrationtest:
    build: integrationtest
    links:
      - webfacade
      - phonefacade
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  stream:
    build: stream
    restart: always
    depends_on:
      rabbit:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
     - rabbit
     - redis
     - dataservice
    ports:
     - "1950:1950"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  redis:
    image: healthcheck/redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports: 
      - "6379:6379"
    volumes:
     - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
     - ../dockervolumes/redis-data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"